name: PR Tests

on:
  pull_request:

jobs:
  check-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Run cargo fmt check
        run: cargo fmt -- --check

      - name: Run cargo test
        run: cargo test --locked --verbose

      - name: Run ignored tests
        run: cargo test --locked --verbose -- --ignored
